version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cashflow_db
    environment:
      POSTGRES_USER: cashflow_user
      POSTGRES_PASSWORD: cashflow_password
      POSTGRES_DB: cashflow_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: cashflow_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  core-go:
    build:
      context: ./services/core-go
      dockerfile: Dockerfile
    container_name: cashflow_core_go
    environment:
      - PORT=8081
      - DATABASE_URL=postgres://cashflow_user:cashflow_password@postgres:5432/cashflow_db?sslmode=disable
      - REDIS_URL=redis:6379
      - SUPERADMIN_EMAIL=odealidj.go@gmail.com
      - SUPERADMIN_PASSWORD=password123
      - SUPERADMIN_NAME=IT Super Admin
      - SUPERADMIN_PHONE=082111391380
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  gateway-go:
    build:
      context: ./services/gateway-go
      dockerfile: Dockerfile
    container_name: cashflow_gateway
    environment:
      - PORT=8080
      - CORE_SERVICE_URL=http://core-go:8081
      - TRACKING_SERVICE_URL=http://tracking-go:8082
      - REDIS_ADDR=redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - core-go
      - redis
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: cashflow_prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - promdata:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    restart: unless-stopped

  k6:
    image: grafana/k6:latest
    container_name: cashflow_k6
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./tests/k6:/scripts
    entrypoint: ["sh", "-c", "trap exit TERM; sleep infinity & wait"]
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  promdata:
