package telemetry

import (
	"strconv"
	"sync"
	"time"

	"github.com/jmoiron/sqlx"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

const (
	// SlowQueryThreshold defines the duration above which a query is recorded as slow
	SlowQueryThreshold = 100 * time.Millisecond
	MaxSlowQueryLogs   = 20
)

// SlowQueryRecord holds detailed information about an individual slow query event
type SlowQueryRecord struct {
	Repository   string    `json:"repository"`
	Operation    string    `json:"operation"`
	QueryPreview string    `json:"query_preview"`
	DurationMs   float64   `json:"duration_ms"`
	Timestamp    time.Time `json:"timestamp"`
	HasError     bool      `json:"has_error"`
}

// SlowQueryTracker manages the in-memory ring-buffer for recent slow queries
type SlowQueryTracker struct {
	mu      sync.RWMutex
	records []SlowQueryRecord
}

var (
	// Global Slow Query Tracker
	GlobalSlowQueryTracker = &SlowQueryTracker{
		records: make([]SlowQueryRecord, 0, MaxSlowQueryLogs),
	}

	// 1. Core HTTP Metrics
	CoreRequestsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "core_http_requests_total",
			Help: "Total HTTP requests handled by Core Go Service",
		},
		[]string{"method", "path", "status_code"},
	)

	CoreRequestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "core_http_request_duration_seconds",
			Help:    "HTTP request latency histogram in seconds for Core Go Service",
			Buckets: []float64{0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0},
		},
		[]string{"method", "path"},
	)

	// 2. Slow Query & Database Execution Metrics
	DBQueryDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "core_db_query_duration_seconds",
			Help:    "PostgreSQL query execution duration histogram in seconds per repository and operation",
			Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5},
		},
		[]string{"repository", "operation"},
	)

	DBSlowQueriesTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "core_db_slow_queries_total",
			Help: "Total queries that exceeded the slow query threshold (>100ms)",
		},
		[]string{"repository", "operation"},
	)

	// 3. Business KPI Metrics
	CashflowEntriesCreatedTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "cashflow_entries_created_total",
			Help: "Total cashflow transactions created real-time in logistics system",
		},
		[]string{"type"}, // "SHIPMENT" or "TOP_UP"
	)

	InvoicesCreatedTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "invoices_created_total",
			Help: "Total invoices generated by billing & finance",
		},
	)

	InvoicesPaidTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "invoices_paid_total",
			Help: "Total invoices successfully marked as paid",
		},
	)
)

// RegisterDBPoolMetrics binds standard Go *sqlx.DB pool stats to Prometheus GaugeFuncs
func RegisterDBPoolMetrics(db *sqlx.DB) {
	if db == nil {
		return
	}

	prometheus.MustRegister(prometheus.NewGaugeFunc(
		prometheus.GaugeOpts{
			Name: "db_connections_open",
			Help: "The number of established connections to PostgreSQL (both in use and idle)",
		},
		func() float64 {
			return float64(db.Stats().OpenConnections)
		},
	))

	prometheus.MustRegister(prometheus.NewGaugeFunc(
		prometheus.GaugeOpts{
			Name: "db_connections_in_use",
			Help: "The number of connections to PostgreSQL currently in use by active queries",
		},
		func() float64 {
			return float64(db.Stats().InUse)
		},
	))

	prometheus.MustRegister(prometheus.NewGaugeFunc(
		prometheus.GaugeOpts{
			Name: "db_connections_idle",
			Help: "The number of idle connections to PostgreSQL in the connection pool",
		},
		func() float64 {
			return float64(db.Stats().Idle)
		},
	))
}

// TrackQuery records query duration and logs to ring-buffer if duration exceeds threshold
func TrackQuery(repository, operation, queryPreview string, start time.Time, err error) {
	duration := time.Since(start)
	durationSeconds := duration.Seconds()
	durationMs := float64(duration.Microseconds()) / 1000.0

	// Prometheus metrics
	DBQueryDuration.WithLabelValues(repository, operation).Observe(durationSeconds)

	if duration >= SlowQueryThreshold {
		DBSlowQueriesTotal.WithLabelValues(repository, operation).Inc()

		// Record in in-memory ring-buffer
		record := SlowQueryRecord{
			Repository:   repository,
			Operation:    operation,
			QueryPreview: queryPreview,
			DurationMs:   durationMs,
			Timestamp:    time.Now(),
			HasError:     err != nil,
		}
		GlobalSlowQueryTracker.Add(record)
	}
}

// Add adds a record to the circular buffer (keeping the latest MaxSlowQueryLogs items)
func (t *SlowQueryTracker) Add(rec SlowQueryRecord) {
	t.mu.Lock()
	defer t.mu.Unlock()

	// Prepend to show newest first
	t.records = append([]SlowQueryRecord{rec}, t.records...)
	if len(t.records) > MaxSlowQueryLogs {
		t.records = t.records[:MaxSlowQueryLogs]
	}
}

// GetRecent returns a copy of recent slow queries
func (t *SlowQueryTracker) GetRecent() []SlowQueryRecord {
	t.mu.RLock()
	defer t.mu.RUnlock()

	out := make([]SlowQueryRecord, len(t.records))
	copy(out, t.records)
	return out
}

// RecordCoreRequest records Core Go HTTP metrics
func RecordCoreRequest(method, path string, statusCode int, durationSeconds float64) {
	CoreRequestsTotal.WithLabelValues(method, path, strconv.Itoa(statusCode)).Inc()
	CoreRequestDuration.WithLabelValues(method, path).Observe(durationSeconds)
}

// RecordCashflowEntryCreated increments cashflow KPI metric
func RecordCashflowEntryCreated(entryType string) {
	CashflowEntriesCreatedTotal.WithLabelValues(entryType).Inc()
}

// RecordInvoiceCreated increments invoice created KPI metric
func RecordInvoiceCreated() {
	InvoicesCreatedTotal.Inc()
}

// RecordInvoicePaid increments invoice paid KPI metric
func RecordInvoicePaid() {
	InvoicesPaidTotal.Inc()
}
